compressionLevel: mixed

nodeLinker: node-modules

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

npmAlwaysAuth: false

npmPublishAccess: public

npmScopes:
  rocketproject:
    npmAuthToken: '${NPM_TOKEN-""}'
