compressionLevel: mixed

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

npmAlwaysAuth: false

npmPublishAccess: public

npmScopes:
  rocketproject:
    npmAuthToken: "${NPM_TOKEN-\"\"}"
